In [ ]:
#| hide
from programming_first_principles.core import prepare_notebook
from programming_first_principles.arrays import my_array
from programming_first_principles.predicates import is_even
from programming_first_principles.helpers import Cost
from functools import partial
from array import array
import operator

In [ ]:
#| hide
prepare_notebook()

## Find

#### Equality & Identity Part 1
* Equality - Operator `==`
  * Same Content/Values
  * each element a[i] == b[i]
* Identity - Operator `is`
  * object in memory same or different?

In [ ]:
a = array('i', [10, 20, 30])
b = array('i', [10, 20, 30])
f'{id(a) = }'
f'{id(b) = }'
f'Equality: {a == b = }'
f'Identity: {a is b = }'
f'eq(a,b) = {operator.eq(a,b) = }'

'id(a) = 4430138720'

'id(b) = 4582447184'

'Equality: a == b = True'

'Identity: a is b = False'

'eq(a,b) = operator.eq(a,b) = True'

#### Equality & Identity Part 2
* Assigment does not make a copy

In [ ]:
c = a
f'{id(a) = }'
f'{id(c) = }'
f'Equality: {a == c = }'
f'Identity: {a is c = }'

'id(a) = 4430138720'

'id(c) = 4430138720'

'Equality: a == c = True'

'Identity: a is c = True'

In [ ]:
#| hide
#| default_exp algorithms.find

#### Find Element
*  `==` equality operator

In [ ]:
#| exports
def find(arr, target):
    index = 0
    for value in arr:          # iterator walk
        if value == target:    # equality
            return index       # found
        index = index + 1
    return -1                  # not found

In [ ]:
arr = array('i', [40, 11, 73, 8, 25, 91, 16, 4])
f'{25 == 25 = } '
f'{25 == 91 = } '

f'{arr[4] == 25 = }'
f'{arr[5] == 91 = }'
f'{find(arr,25) = }'
f'{find(arr,99) = }'

'25 == 25 = True '

'25 == 91 = False '

'arr[4] == 25 = True'

'arr[5] == 91 = True'

'find(arr,25) = 4'

'find(arr,99) = -1'

#### find_if

In [ ]:
#| exports
def find_if(a, first, last, pred):
    for i in range(first, last):
        if pred(a[i]):
            return i
    return last

In [ ]:
# from programming_first_principles.predicates import is_even
scores_fi = [5, 3, 40, 10, 20, 60, 75, 80]
f'{find_if(scores_fi, 0, len(scores_fi), is_even) = }'

'find_if(scores_fi, 0, len(scores_fi), is_even) = 2'

In [ ]:
find_if_measure = Cost(repeats=1)
_ = find_if_measure.run(find_if, scores_fi, 0, len(arr), lambda x: x == 10,
         name='find_if', shape='found at 4', operations=('predicates','ms'))
_ = find_if_measure.run(find_if, scores_fi, 0, len(arr), lambda x: x == 90,
         name='find_if', shape='absent', operations=('predicates','ms'))
find_if_measure.frame

      algo       shape  n comparisons  predicates swaps      ms
0  find_if  found at 4  8        None           4  None  0.0031
1  find_if      absent  8        None           8  None  0.0023

#### find_if_not

In [ ]:
#| exports
def find_if_not(a, first, last, pred):
    for i in range(first, last):
        if not pred(a[i]):
            return i
    return last

In [ ]:
scores_fin = [5, 3, 40, 10, 20, 60, 75, 80]
f'{find_if_not(scores_fin, 0, len(scores_fin), is_even) = }'

'find_if_not(scores_fin, 0, len(scores_fin), is_even) = 0'

In [ ]:
fin_measure = Cost(repeats=1)
_ = fin_measure.run(find_if_not, [40, 8, 16, 4, 11, 25], 0, 6, is_even,
         name='find_if_not', shape='fails at 4', operations=('predicates','ms'))
_ = fin_measure.run(find_if_not, [40, 8, 16, 4, 2, 10], 0, 6, is_even,
         name='find_if_not', shape='all pass', operations=('predicates','ms'))
fin_measure.frame

          algo       shape  n comparisons  predicates swaps      ms
0  find_if_not  fails at 4  6        None           5  None  0.0024
1  find_if_not    all pass  6        None           6  None  0.0030

#### find_mismatch

In [ ]:
#| exports
def find_mismatch(a, f0, l0, b, f1, l1, r):
    while f0 != l0 and f1 != l1 and r(a[f0], b[f1]):
        f0 += 1
        f1 += 1
    return f0, f1

In [ ]:
# a = [1, 2, 9, 4]
# b = [1, 2, 4]
a = [1, 2, 9, 4]
b = [7, 7, 1, 2, 4, 5]

f'{find_mismatch(a, 0, len(a), b, 2, 5, operator.eq) = }'  # (2, 2)

'find_mismatch(a, 0, len(a), b, 2, 5, operator.eq) = (2, 4)'

In [ ]:
mm = Cost(repeats=1)
_ = mm.run(find_mismatch, [1, 2, 9, 4], 0, 4, [1, 2, 4, 5], 0, 4, operator.eq,
           name='find_mismatch', shape='mismatch at 2', operations=('predicates','ms'))
_ = mm.run(find_mismatch, [1, 2, 3, 4], 0, 4, [1, 2, 3, 4], 0, 4, operator.eq,
           name='find_mismatch', shape='equal', operations=('predicates','ms'))
mm.frame

            algo          shape  n comparisons  predicates swaps      ms
0  find_mismatch  mismatch at 2  4        None           3  None  0.0022
1  find_mismatch          equal  4        None           4  None  0.0021

#### find_adjacent_mismatch

In [ ]:
#| exports
def find_adjacent_mismatch(a, first, last, pred):
    if first == last:
        return last
    x = a[first]
    first += 1
    while first != last and pred(x, a[first]):
        x = a[first]
        first += 1
    return first

In [ ]:
a = [1, 2, 2, 0]
f'{find_adjacent_mismatch(a, 0, len(a), lambda x, y: x <= y) = }'

'find_adjacent_mismatch(a, 0, len(a), lambda x, y: x <= y) = 3'

In [ ]:
adj = Cost(repeats=1)
_ = adj.run(find_adjacent_mismatch, [2, 1, 3, 4], 0, 4, lambda x, y: x <= y,
            name='find_adjacent_mismatch', shape='breaks at 1', operations=('predicates','ms'))
_ = adj.run(find_adjacent_mismatch, [1, 2, 3, 4], 0, 4, lambda x, y: x <= y,
            name='find_adjacent_mismatch', shape='ordered', operations=('predicates','ms'))
adj.frame

,algo,shape,n,comparisons,predicates,swaps,ms
0,find_adjacent_mismatch,breaks at 1,4,None,1,None,0.0018
1,find_adjacent_mismatch,ordered,4,None,3,None,0.0025

#### Count

In [ ]:
#| exports
def count_if(a, first, last, pred):
    count = 0 
    for i in range(first, last):
        if pred(a[i]):
            count += 1
    return count

In [ ]:
t = array("i",[1,2,1,2,3,3,5,6,2])
f'{count_if(t, 0, len(t), partial(operator.eq, 2)) = }'
f'{t.count(2) = }'

'count_if(t, 0, len(t), partial(operator.eq, 2)) = 3'

't.count(2) = 3'

In [ ]:
cnt = Cost(repeats=1)
t = [1, 2, 1, 2, 3, 3, 5, 6, 2]
_ = cnt.run(count_if, t, 0, len(t), partial(operator.eq, 2),
            name='count_if', shape='three hits', operations=('predicates','ms'))    
_ = cnt.run(count_if, t, 0, len(t), partial(operator.eq, 9),    
            name='count_if', shape='none', operations=('predicates','ms'))
cnt.frame

       algo       shape  n comparisons  predicates swaps      ms
0  count_if  three hits  9        None           9  None  0.0035
1  count_if        none  9        None           9  None  0.0018

#### Membership
* **Container** - `__contains__`
* val `in` sequence
* in and not in

In [ ]:
t = array("i",[1,2,1,2,3,3,5,6,2])
f'{my_array.__contains__(503) = }'
f'{503 in my_array = }'
f'{506 in my_array = }'

'my_array.__contains__(503) = True'

'503 in my_array = True'

'506 in my_array = False'

## Quantifier
* A quantifier says how many elements of a range satisfy a predicate, and the function returns only that yes or no.

#### all_of

In [ ]:
#| exports
def all_of(a, first, last, pred): 
    return find_if_not(a, first, last, pred) == last

In [ ]:
scores_ao = [5, 3, 40, 10, 20, 60, 75, 80]
f'{all_of(scores_ao, 0, len(scores_ao), is_even) = }'

'all_of(scores_ao, 0, len(scores_ao), is_even) = False'

In [ ]:
ao = Cost(repeats=1)
_ = ao.run(all_of, [5, 3, 40, 10], 0, 4, is_even,
           name='all_of', shape='fails at 0', operations=('predicates','ms'))   
_ = ao.run(all_of, [40, 8, 16, 4], 0, 4, is_even,
           name='all_of', shape='all pass', operations=('predicates','ms'))
ao.frame

     algo       shape  n comparisons  predicates swaps      ms
0  all_of  fails at 0  4        None           1  None  0.0021
1  all_of    all pass  4        None           4  None  0.0025

#### any_of

In [ ]:
#| exports
def any_of(a, first, last, pred):
    return find_if(a, first, last, pred) != last

In [ ]:
scores_any = [5, 3, 40, 10, 20, 60, 75, 80]
f'{any_of(scores_any, 0, len(scores_any), is_even) = }'

'any_of(scores_any, 0, len(scores_any), is_even) = True'

In [ ]:
any_m = Cost(repeats=1)
_ = any_m.run(any_of, [5, 3, 40, 10], 0, 4, is_even,
              name='any_of', shape='found at 2', operations=('predicates','ms'))
_ = any_m.run(any_of, [5, 3, 7, 9], 0, 4, is_even,
              name='any_of', shape='absent', operations=('predicates','ms'))
any_m.frame

     algo       shape  n comparisons  predicates swaps      ms
0  any_of  found at 2  4        None           3  None  0.0027
1  any_of      absent  4        None           4  None  0.0032

#### none_of

In [ ]:
#| exports
def none_of(a, first, last, pred):
    return find_if(a, first, last, pred) == last

In [ ]:
scores_none = [5, 3, 40, 10, 20, 60, 75, 80]
f'{none_of(scores_none, 0, len(scores_none), is_even) = }'

'none_of(scores_none, 0, len(scores_none), is_even) = False'

In [ ]:
none_m = Cost(repeats=1)
_ = none_m.run(none_of, [5, 3, 40, 10], 0, 4, is_even,
               name='none_of', shape='found at 2', operations=('predicates','ms'))
_ = none_m.run(none_of, [5, 3, 7, 9], 0, 4, is_even,
               name='none_of', shape='none', operations=('predicates','ms'))
none_m.frame

      algo       shape  n comparisons  predicates swaps      ms
0  none_of  found at 2  4        None           3  None  0.0027
1  none_of        none  4        None           4  None  0.0018