# Rearrangement

In [ ]:
#| hide
from programming_first_principles.core import prepare_notebook
from programming_first_principles.helpers.predicates import above_35, below_35
from programming_first_principles.helpers.cost import Cost
from functools import partial
from array import array

In [ ]:
#| hide
prepare_notebook()

In [ ]:
#| hide
#| default_exp algorithms.rearrange

#### Swap

In [ ]:
#| exports
def swap(a, i, j):
    a[i], a[j] = a[j], a[i]

In [ ]:
arr = [1, 2, 3, 4, 5]
f'{arr = }'
swap(arr, 0, 1)
f'{arr = }'

'arr = [1, 2, 3, 4, 5]'

'arr = [2, 1, 3, 4, 5]'

#### Reverse

In [ ]:
#| exports
def reverse(seq,first,last):
  """
  Reverses elements in the half-open range [f, l) using swap and iteration
  """
  last -= 1
  while first < last:
    seq[first], seq[last] = seq[last], seq[first]
    first += 1
    last -= 1

In [ ]:
arr = [1,2,3,4,5,6,7,8]
f'Before: {arr}'
reverse(arr,1, 6)
f'After:  {arr}'

'Before: [1, 2, 3, 4, 5, 6, 7, 8]'

'After:  [1, 6, 5, 4, 3, 2, 7, 8]'

In [ ]:
rev_swap = Cost(repeats=1)
_ = rev_swap.run(reverse, [1, 2, 3, 4, 5, 6, 7, 8], 0, 8,
                 name='reverse', shape='even', operations=('swaps','ms'))
_ = rev_swap.run(reverse, [1, 2, 3, 4, 5], 0, 5,
                 name='reverse', shape='odd', operations=('swaps','ms'))
rev_swap.frame

      algo shape  n comparisons predicates  swaps      ms
0  reverse  even  8        None       None      4  0.0024
1  reverse   odd  5        None       None      2  0.0022

In [ ]:
#| exports
def reverse_py(seq, first, last):
    """Reverses elements in the half-open range [first, last) using slicing"""
    seq[first:last] = seq[first:last][::-1]

In [ ]:
arr1 = [1,2,3,4,5,6,7,8]
f'Before: {arr1}'
reverse_py(arr1,1, 6)
f'After:  {arr1}'

'Before: [1, 2, 3, 4, 5, 6, 7, 8]'

'After:  [1, 6, 5, 4, 3, 2, 7, 8]'

In [ ]:
rev_slice = Cost(repeats=1)
_ = rev_slice.run(reverse, [1, 2, 3, 4, 5, 6, 7, 8], 0, 8,
                  name='reverse', shape='even', operations=('swaps','ms'))
_ = rev_slice.run(reverse, [1, 2, 3, 4, 5], 0, 5,
                  name='reverse', shape='odd', operations=('swaps','ms'))
rev_slice.frame

      algo shape  n comparisons predicates  swaps      ms
0  reverse  even  8        None       None      4  0.0022
1  reverse   odd  5        None       None      2  0.0013

#### Rotate

In [ ]:
#| exports
def rotate(a, first, middle, last):
    reverse(a, first, middle)
    reverse(a, middle, last)
    reverse(a, first, last)
    return first + (last - middle)

In [ ]:
arr = [0, 1, 2, 3, 4, 5]
f'Before: {arr}'
f'{rotate(arr, 0, 2, 6) = }'
f'After:  {arr}'

'Before: [0, 1, 2, 3, 4, 5]'

'rotate(arr, 0, 2, 6) = 4'

'After:  [2, 3, 4, 5, 0, 1]'

In [ ]:
rot = Cost(repeats=1)
_ = rot.run(rotate, [0, 1, 2, 3, 4, 5], 0, 2, 6,
            name='rotate', shape='middle at 2', operations=('swaps','ms'))
_ = rot.run(rotate, [0, 1, 2, 3, 4, 5], 0, 0, 6,
            name='rotate', shape='middle at start', operations=('swaps','ms'))
_ = rot.run(rotate, [0, 1, 2, 3, 4, 5], 0, 6, 6,
            name='rotate', shape='middle at end', operations=('swaps','ms'))
rot.frame

     algo            shape  n comparisons predicates  swaps      ms
0  rotate      middle at 2  6        None       None      6  0.0027
1  rotate  middle at start  6        None       None      6  0.0019
2  rotate    middle at end  6        None       None      6  0.0016

In [ ]:
#| exports
def rotate_py(a, first, middle, last):
    reverse_py(a, first, middle)
    reverse_py(a, middle, last)
    reverse_py(a, first, last)
    return first + (last - middle)

In [ ]:
arr = [0, 1, 2, 3, 4, 5]
f'{rotate_py(arr, 0, 0, 6) = }'
f'{rotate_py(arr, 0, 6, 6) = }'
f'{arr = }'

'rotate_py(arr, 0, 0, 6) = 6'

'rotate_py(arr, 0, 6, 6) = 0'

'arr = [0, 1, 2, 3, 4, 5]'

#### Slide

In [ ]:
#| exports
def slide(a, f, l, p):
    if p < f:
        return p, rotate(a, p, f, l)
    if l < p:
        return rotate(a, f, l, p), p
    return f, l

In [ ]:
a = [0, 1, 2, 3, 4, 5]

nf, nl = slide(a, 0, 2, 6)

f'{nf = }, {nl = }'
f'{a = }'
f'{slide(a, nf, nl, 0) = }'
f'{a = }'
f'{slide(a, 3, 5, 0) = }'
f'{a = }'

'nf = 4, nl = 6'

'a = [2, 3, 4, 5, 0, 1]'

'slide(a, nf, nl, 0) = (0, 2)'

'a = [0, 1, 2, 3, 4, 5]'

'slide(a, 3, 5, 0) = (0, 2)'

'a = [3, 4, 0, 1, 2, 5]'

In [ ]:
sld = Cost(repeats=1)
_ = sld.run(slide, [0, 1, 2, 3, 4, 5], 0, 2, 6,
            name='slide', shape='p after range', operations=('swaps','ms'))
_ = sld.run(slide, [0, 1, 2, 3, 4, 5], 3, 5, 0,
            name='slide', shape='p before range', operations=('swaps','ms'))
_ = sld.run(slide, [0, 1, 2, 3, 4, 5], 0, 2, 1,
            name='slide', shape='p inside range', operations=('swaps','ms'))
sld.frame

    algo           shape  n comparisons predicates  swaps      ms
0  slide   p after range  6        None       None      6  0.0032
1  slide  p before range  6        None       None      4  0.0030
2  slide  p inside range  6        None       None      0  0.0011